pipeline {
    agent none 
    stages {
        stage('Build') { // Pipeline inicial 
            agent {
                docker { // Descarga una imagen de Python en Docker
                    image 'python:3.12.1-alpine3.19' 
                }
            }
            steps { // Eejcuta una simple aplicación en Python
                sh 'python -m py_compile sources/add2vals.py sources/calc.py' 
                stash(name: 'compiled-results', includes: 'sources/*.py*') 
            }
        }
    }
}

