trigger:
  branches:
    include:
      - main

stages:
- stage: Docker_Build_and_Compose
  jobs:
  - job: Build_and_Compose
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo 'Starting Docker Build and Compose'
        displayName: 'Starting Docker Build and Compose'

      - task: Docker@2
        displayName: 'Build Docker Image'
        inputs:
          command: 'build'
          Dockerfile: '**/Dockerfile'
          tags: 'latest'

      - task: Docker@2
        displayName: 'Push Docker Image to Registry'
        inputs:
          command: 'push'
          tags: 'latest'
          containerRegistry: 'trabajovscontenedor'

      - task: Docker@2
        displayName: 'Docker Compose Up'
        inputs:
          command: 'composeUp'
          dockerComposeFile: '**/docker-compose.yml'
          removeContainersOnPull: true
          detachedService: true

- stage: SonarQube_Analysis
  jobs:
  - job: Analyze
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: SonarQubePrepare@4
        inputs:
          SonarQube: 'SonarQube' 
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: 'ProyectoVS-SonarQube-Key' 
          cliSources: '.'

      - script: docker build -t my-image .
      - script: docker save my-image | gzip > my-image.tar.gz

      - task: SonarQubeAnalyze@4
      - task: SonarQubePublish@4
        inputs:
          pollingTimeoutSec: '300'
